### ISSUE TITLE
Fails Attempting to add user to filevault

### ISSUE THREAD

**Issue by manicslothpdx** [square/fde-rekey#1]
Here are the logs, as previously mentioned on Slack:

`Mar 14 17:11:31 bmarks-mp2013 installer[6848]: Starting installation:
Mar 14 17:11:31 bmarks-mp2013 installer[6848]: Configuring volume "Macintosh SSD"
Mar 14 17:11:31 bmarks-mp2013 installer[6848]: Preparing disk for local booted install.
Mar 14 17:11:31 bmarks-mp2013 installer[6848]: Free space on "Macintosh SSD": 492.23 GB (492231831552 bytes).
Mar 14 17:11:31 bmarks-mp2013 installer[6848]: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.6848QholQw"
Mar 14 17:11:31 bmarks-mp2013 installer[6848]: IFPKInstallElement (1 packages)
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: Adding client PKInstallDaemonClient pid=6848, uid=0 (/usr/sbin/installer)
Mar 14 17:11:31 bmarks-mp2013 installer[6848]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: ----- Begin install -----
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: request=PKInstallRequest <1 packages, destination=/>
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: packages=(
        "PKLeopardPackage <file://localhost/Library/Application%20Support/JAMF/Downloads/sfdc-fde-rekey.pkg#fde-rekey.pkg>"
    )
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: Session UUID file exists - will not overwrite /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/B574324D-7714-4FC1-837F-D8F20163A1DE.activeSandbox
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: Extracting file://localhost/Library/Application%20Support/JAMF/Downloads/sfdc-fde-rekey.pkg#fde-rekey.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/B574324D-7714-4FC1-837F-D8F20163A1DE.activeSandbox/Root, uid=0)
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: prevent user idle system sleep
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: suspending backupd
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/B574324D-7714-4FC1-837F-D8F20163A1DE.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/B574324D-7714-4FC1-837F-D8F20163A1DE.activeSandbox
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/B574324D-7714-4FC1-837F-D8F20163A1DE.activeSandbox/Root (1 items) to /
Mar 14 17:11:31 bmarks-mp2013 installd[1105]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.GwrS4o/Scripts/com.github.square.fderekey.8yW33I
Mar 14 17:11:32 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:32.304 sysadminctl[6857:28555970] Creating user record…
Mar 14 17:11:32 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:32.910 sysadminctl[6857:28555970] Assigning UID: 2
Mar 14 17:11:32 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:32.927 sysadminctl[6857:28555970] Creating home directory at /Users/fderekey
Mar 14 17:11:34 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:34.377 sysadminctl[6872:28556102] Killing all processes for UID 2
Mar 14 17:11:34 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:34.377 sysadminctl[6872:28556102] Securely removing fderekey's home at /Users/fderekey
Mar 14 17:11:34 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:34.490 sysadminctl[6872:28556102] Deleting Public share point for fderekey
Mar 14 17:11:34 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:34.492 sysadminctl[6872:28556102] Deleting record for fderekey
Mar 14 17:11:34 bmarks-mp2013 installd[1105]: ./postinstall: 2017-03-14 17:11:34.507 sysadminctl[6872:28556102] AOSKit INFO: Disabling BTMM for user, no zone found for uid=2, usersToZones: (null)
Mar 14 17:11:34 bmarks-mp2013 installd[1105]: ./postinstall: EROOR! Failed to add user "fderekey" to FileVault...
Mar 14 17:11:35 bmarks-mp2013 installd[1105]: PackageKit: releasing backupd
Mar 14 17:11:35 bmarks-mp2013 installd[1105]: PackageKit: allow user idle system sleep
Mar 14 17:11:35 bmarks-mp2013 installd[1105]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “sfdc-fde-rekey.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Library/Application%20Support/JAMF/Downloads/sfdc-fde-rekey.pkg#fde-rekey.pkg, PKInstallPackageIdentifier=com.github.square.fderekey, NSLocalizedDescription=An error occurred while running scripts from the package “sfdc-fde-rekey.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201csfdc-fde-rekey.pkg\U201d.";
        NSURL = "file://localhost/Library/Application%20Support/JAMF/Downloads/sfdc-fde-rekey.pkg#fde-rekey.pkg";
        PKInstallPackageIdentifier = "com.github.square.fderekey";
    }
Mar 14 17:11:35 bmarks-mp2013 installd[1105]: PackageKit: Running idle tasks
Mar 14 17:11:35 bmarks-mp2013 installer[6848]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “sfdc-fde-rekey.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Library/Application%20Support/JAMF/Downloads/sfdc-fde-rekey.pkg#fde-rekey.pkg, PKInstallPackageIdentifier=com.github.square.fderekey, NSLocalizedDescription=An error occurred while running scripts from the package “sfdc-fde-rekey.pkg”.}
Mar 14 17:11:35 bmarks-mp2013 installd[1105]: PackageKit: Removing client PKInstallDaemonClient pid=6848, uid=0 (/usr/sbin/installer)
Mar 14 17:11:35 bmarks-mp2013 installd[1105]: PackageKit: Done with sandbox removals
Mar 14 17:11:36 bmarks-mp2013 installer[6848]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.`

**Comment by weswhet** [comment]
@manicslothpdx Can you try a few things?
`sudo sysadminctl -addUser 'fderekey' -password 'test' -UID 2`
`git clone https://github.com/square/fde-rekey.git`
`cd fde-rekey`
`sudo ./payload/var/root/fdeadduser fderekey test`
`sudo fdesetup list`
You should see user 'fderekey' in the FileVault list.

If you don't see a 'fderekey' in the user list can you provide the output of `fdesetup status`

**Comment by manicslothpdx** [comment]
The command `fdesetup list` shows my user name on this test Mac and a long string instead of the user name fdeadduser: 10D5D1E2-62A5-482E-B1E0-E05E74B41D71

The command `fdesetup` status gives the following results:

`FileVault is On.
FileVault master keychain appears to be installed.`

**Comment by weswhet** [comment]
Issue here appeared to be configuration profile for password strengths on accounts. and the random password generator didn't meet the requirements. 

This is fixed with 124cea08ad59ca18755b8be482dc7b6df3746683

Which makes the new password 30 characters, with upper, lower, digit and special characters

**Comment by tyger15** [comment]
Seems this issue is present again with the current release on 10.12.5
